import { z } from "zod";

export const LocalBridgeErrorCode = {
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_DISABLED: "PROJECT_DISABLED",
  PROJECT_ALREADY_EXISTS: "PROJECT_ALREADY_EXISTS",
  PROJECT_ROOT_NOT_FOUND: "PROJECT_ROOT_NOT_FOUND",
  PROJECT_ROOT_NOT_DIRECTORY: "PROJECT_ROOT_NOT_DIRECTORY",
  PATH_NOT_ALLOWED: "PATH_NOT_ALLOWED",
  PATH_TRAVERSAL: "PATH_TRAVERSAL",
  PATH_SYMLINK_ESCAPE: "PATH_SYMLINK_ESCAPE",
  PATH_UNC_NOT_ALLOWED: "PATH_UNC_NOT_ALLOWED",
  PATH_DEVICE_NOT_ALLOWED: "PATH_DEVICE_NOT_ALLOWED",
  PATH_ADS_NOT_ALLOWED: "PATH_ADS_NOT_ALLOWED",
  PATH_INVALID_WINDOWS_NAME: "PATH_INVALID_WINDOWS_NAME",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  BINARY_FILE: "BINARY_FILE",
  NOT_A_DIRECTORY: "NOT_A_DIRECTORY",
  FILE_NOT_REGULAR: "FILE_NOT_REGULAR",
  FILE_ENCODING_UNSUPPORTED: "FILE_ENCODING_UNSUPPORTED",
  FILE_LINE_TOO_LONG: "FILE_LINE_TOO_LONG",
  SENSITIVE_FILE_BLOCKED: "SENSITIVE_FILE_BLOCKED",
  INVALID_CURSOR: "INVALID_CURSOR",
  FILE_ACCESS_DENIED: "FILE_ACCESS_DENIED",
  PROJECT_READ_ONLY: "PROJECT_READ_ONLY",
  FILE_ALREADY_EXISTS: "FILE_ALREADY_EXISTS",
  PARENT_DIRECTORY_NOT_FOUND: "PARENT_DIRECTORY_NOT_FOUND",
  FILE_CONFLICT: "FILE_CONFLICT",
  PATCH_NOT_FOUND: "PATCH_NOT_FOUND",
  PATCH_AMBIGUOUS: "PATCH_AMBIGUOUS",
  FILE_WRITE_FAILED: "FILE_WRITE_FAILED",
  FILE_DELETE_FAILED: "FILE_DELETE_FAILED",
  FILE_SYMLINK_WRITE_BLOCKED: "FILE_SYMLINK_WRITE_BLOCKED",
  BACKUP_NOT_FOUND: "BACKUP_NOT_FOUND",
  BACKUP_LIMIT_EXCEEDED: "BACKUP_LIMIT_EXCEEDED",
  RESTORE_CONFLICT: "RESTORE_CONFLICT",
  FILE_BUSY: "FILE_BUSY",
  GIT_NOT_AVAILABLE: "GIT_NOT_AVAILABLE",
  GIT_NOT_REPOSITORY: "GIT_NOT_REPOSITORY",
  GIT_REPOSITORY_BOUNDARY: "GIT_REPOSITORY_BOUNDARY",
  GIT_UNSAFE_REPOSITORY: "GIT_UNSAFE_REPOSITORY",
  GIT_TIMEOUT: "GIT_TIMEOUT",
  GIT_PROCESS_FAILED: "GIT_PROCESS_FAILED",
  GIT_OUTPUT_TOO_LARGE: "GIT_OUTPUT_TOO_LARGE",
  GIT_DIFF_TOO_LARGE: "GIT_DIFF_TOO_LARGE",
  GIT_PARSE_ERROR: "GIT_PARSE_ERROR",
  GIT_SENSITIVE_PATH_BLOCKED: "GIT_SENSITIVE_PATH_BLOCKED",
  GIT_SYMLINK_DIFF_BLOCKED: "GIT_SYMLINK_DIFF_BLOCKED",
  GIT_SUBMODULE_NOT_SUPPORTED: "GIT_SUBMODULE_NOT_SUPPORTED",
  GIT_WORKTREE_CONFLICT: "GIT_WORKTREE_CONFLICT",
  GIT_NOTHING_STAGED: "GIT_NOTHING_STAGED",
  GIT_INVALID_BRANCH_NAME: "GIT_INVALID_BRANCH_NAME",
  GIT_BRANCH_NOT_FOUND: "GIT_BRANCH_NOT_FOUND",
  GIT_BRANCH_EXISTS: "GIT_BRANCH_EXISTS",
  GIT_PATH_NOT_FOUND: "GIT_PATH_NOT_FOUND",
  GIT_WRITE_FAILED: "GIT_WRITE_FAILED",
  PROJECT_EXECUTION_DISABLED: "PROJECT_EXECUTION_DISABLED",
  PROJECT_EXECUTION_REQUIRES_WRITE_ACCESS: "PROJECT_EXECUTION_REQUIRES_WRITE_ACCESS",
  COMMAND_BLOCKED: "COMMAND_BLOCKED",
  COMMAND_UNSUPPORTED: "COMMAND_UNSUPPORTED",
  COMMAND_EXECUTION_FAILED: "COMMAND_EXECUTION_FAILED",
  COMMAND_TIMEOUT: "COMMAND_TIMEOUT",
  COMMAND_OUTPUT_TOO_LARGE: "COMMAND_OUTPUT_TOO_LARGE",
  COMMAND_ARGUMENTS_TOO_LARGE: "COMMAND_ARGUMENTS_TOO_LARGE",
  COMMAND_TOOL_NOT_AVAILABLE: "COMMAND_TOOL_NOT_AVAILABLE",
  COMMAND_SCRIPT_NOT_FOUND: "COMMAND_SCRIPT_NOT_FOUND",
  COMMAND_INVALID_WORKING_DIRECTORY: "COMMAND_INVALID_WORKING_DIRECTORY",
  COMMAND_INVALID_ENV: "COMMAND_INVALID_ENV",
  RUNNER_OFFLINE: "RUNNER_OFFLINE",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  JOB_CAPACITY_EXCEEDED: "JOB_CAPACITY_EXCEEDED",
  JOB_RATE_LIMITED: "JOB_RATE_LIMITED",
  JOB_TIMEOUT: "JOB_TIMEOUT",
  JOB_INVALID_STATE: "JOB_INVALID_STATE",
  INVALID_JOB_CURSOR: "INVALID_JOB_CURSOR",
  BUILD_SCRIPT_NOT_FOUND: "BUILD_SCRIPT_NOT_FOUND",
  TEST_SCRIPT_NOT_FOUND: "TEST_SCRIPT_NOT_FOUND",
  PATCH_CONFLICT: "PATCH_CONFLICT",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_REQUEST: "INVALID_REQUEST",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PROTOCOL_VERSION_UNSUPPORTED: "PROTOCOL_VERSION_UNSUPPORTED",
  RPC_TIMEOUT: "RPC_TIMEOUT",
  RUNNER_DISCONNECTED: "RUNNER_DISCONNECTED",
  RUNNER_BUSY: "RUNNER_BUSY",
  RPC_MESSAGE_TOO_LARGE: "RPC_MESSAGE_TOO_LARGE",
  RPC_INVALID_RESPONSE: "RPC_INVALID_RESPONSE",
  RPC_REMOTE_ERROR: "RPC_REMOTE_ERROR",
  APPROVAL_NOT_FOUND: "APPROVAL_NOT_FOUND",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
  APPROVAL_EXPIRED: "APPROVAL_EXPIRED",
  APPROVAL_ALREADY_RESOLVED: "APPROVAL_ALREADY_RESOLVED",
  APPROVAL_PAYLOAD_MISMATCH: "APPROVAL_PAYLOAD_MISMATCH",
  AI_ACCESS_PAUSED: "AI_ACCESS_PAUSED",
  POLICY_DENIED: "POLICY_DENIED",
  TRUST_POLICY_INVALID: "TRUST_POLICY_INVALID",
} as const;

export type LocalBridgeErrorCode =
  (typeof LocalBridgeErrorCode)[keyof typeof LocalBridgeErrorCode];

export const JsonRpcStandardErrorCode = {
  ParseError: -32700,
  InvalidRequest: -32600,
  MethodNotFound: -32601,
  InvalidParams: -32602,
  InternalError: -32603,
  DuplicateRequestId: -32001,
} as const;

export type JsonRpcStandardErrorCode =
  (typeof JsonRpcStandardErrorCode)[keyof typeof JsonRpcStandardErrorCode];

export class RemoteRpcError extends Error {
  readonly code: number;
  readonly data?: unknown;

  constructor(code: number, message: string, data?: unknown) {
    super(message);
    this.name = "RemoteRpcError";
    this.code = code;
    this.data = data;
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

export const LocalBridgeErrorSchema = z.object({
  code: z.nativeEnum(LocalBridgeErrorCode),
  message: z.string(),
  details: z.record(z.unknown()).optional(),
});

export type LocalBridgeErrorPayload = z.infer<typeof LocalBridgeErrorSchema>;

export class LocalBridgeError extends Error {
  readonly code: LocalBridgeErrorCode;
  readonly details?: Record<string, unknown>;

  constructor(
    code: LocalBridgeErrorCode,
    message: string,
    details?: Record<string, unknown>
  ) {
    super(message);
    this.name = "LocalBridgeError";
    this.code = code;
    this.details = details;
    Object.setPrototypeOf(this, new.target.prototype);
  }

  toJSON(): LocalBridgeErrorPayload {
    return {
      code: this.code,
      message: this.message,
      ...(this.details ? { details: this.details } : {}),
    };
  }
}
