import fs from "node:fs";
import path from "node:path";

console.log("Runtime running in cwd: " + process.cwd());
fs.writeFileSync(path.join(process.cwd(), "worktree-output.txt"), "generated by worktree runtime\n", "utf-8");
const interval = setInterval(() => {}, 100);
process.on("SIGTERM", () => {
  clearInterval(interval);
  process.exit(0);
});
