export const RunnerRpcMethods = {
  Hello: "runner.hello",
  SystemPing: "system.ping",
  SystemInfo: "system.info",
  SystemShutdown: "system.shutdown",
  ProjectList: "project.list",
  ProjectInfo: "project.info",
  ProjectValidate: "project.validate",
  DirectoryList: "directory.list",
  FileStat: "file.stat",
  FileRead: "file.read",
  FileCreate: "file.create",
  FileWrite: "file.write",
  FilePatch: "file.patch",
  FileDelete: "file.delete",
  FileRestore: "file.restore",
  GitInfo: "git.info",
  GitStatus: "git.status",
  GitDiff: "git.diff",
  GitLog: "git.log",
  CommandClassify: "command.classify",
  CommandRun: "command.run",
  JobStart: "job.start",
  JobStatus: "job.status",
  JobLogs: "job.logs",
  JobCancel: "job.cancel",
  JobList: "job.list",
  BuildStart: "build.start",
  TestStart: "test.start",
  ProjectAuthorize: "project.authorize",
  ProjectSetAccess: "project.setAccess",
  ProjectSetExecution: "project.setExecution",
  ProjectRemove: "project.remove",
  ProjectEnable: "project.enable",
  ProjectDisable: "project.disable",
  ApprovalCreate: "approval.create",
  ApprovalResolve: "approval.resolve",
  ApprovalList: "approval.list",
  ApprovalGet: "approval.get",
  JobCancelAll: "job.cancelAll",
  ProjectSetTrustPolicy: "project.setTrustPolicy",
  ProjectSessionTrust: "project.sessionTrust",
  ApprovalBulkResolve: "approval.bulkResolve",
  ApprovalSetMode: "approval.setMode",
  GitStage: "git.stage",
  GitUnstage: "git.unstage",
  GitBranchCreate: "git.branchCreate",
  GitBranchSwitch: "git.branchSwitch",
  GitCommit: "git.commit",
  CodeDocumentSymbols: "code.document_symbols",
  CodeWorkspaceSymbols: "code.workspace_symbols",
  CodeDefinition: "code.definition",
  CodeReferences: "code.references",
  CodeHover: "code.hover",
  CodeDiagnostics: "code.diagnostics",
  CodeCallHierarchy: "code.call_hierarchy",
  CodeImpact: "code.impact",
  LspStatus: "lsp.status",
  LspRestart: "lsp.restart",
  LspStop: "lsp.stop",
  WorktreeCreate: "worktree.create",
  WorktreeList: "worktree.list",
  WorktreeStatus: "worktree.status",
  WorktreeDiff: "worktree.diff",
  WorktreeRemove: "worktree.remove",
} as const;

export type RunnerRpcMethod =
  (typeof RunnerRpcMethods)[keyof typeof RunnerRpcMethods];

export const RunnerMethod = {
  RUNNER_HELLO: RunnerRpcMethods.Hello,
  SYSTEM_PING: RunnerRpcMethods.SystemPing,
  SYSTEM_INFO: RunnerRpcMethods.SystemInfo,
  PROJECT_VALIDATE: RunnerRpcMethods.ProjectValidate,
  DIRECTORY_LIST: RunnerRpcMethods.DirectoryList,
  FILE_STAT: RunnerRpcMethods.FileStat,
  FILE_READ: RunnerRpcMethods.FileRead,
  FILE_CREATE: RunnerRpcMethods.FileCreate,
  FILE_WRITE: RunnerRpcMethods.FileWrite,
  FILE_PATCH: RunnerRpcMethods.FilePatch,
  FILE_DELETE: RunnerRpcMethods.FileDelete,
  FILE_RESTORE: RunnerRpcMethods.FileRestore,
  GIT_INFO: RunnerRpcMethods.GitInfo,
  GIT_STATUS: RunnerRpcMethods.GitStatus,
  GIT_DIFF: RunnerRpcMethods.GitDiff,
  GIT_LOG: RunnerRpcMethods.GitLog,
  COMMAND_CLASSIFY: RunnerRpcMethods.CommandClassify,
  COMMAND_RUN: RunnerRpcMethods.CommandRun,
  FILE_SEARCH: "file.search",
  TEXT_SEARCH: "text.search",
  JOB_START: RunnerRpcMethods.JobStart,
  JOB_STATUS: RunnerRpcMethods.JobStatus,
  JOB_LOGS: RunnerRpcMethods.JobLogs,
  JOB_CANCEL: RunnerRpcMethods.JobCancel,
  JOB_LIST: RunnerRpcMethods.JobList,
  BUILD_START: RunnerRpcMethods.BuildStart,
  TEST_START: RunnerRpcMethods.TestStart,
  WORKTREE_CREATE: RunnerRpcMethods.WorktreeCreate,
  WORKTREE_LIST: RunnerRpcMethods.WorktreeList,
  WORKTREE_STATUS: RunnerRpcMethods.WorktreeStatus,
  WORKTREE_DIFF: RunnerRpcMethods.WorktreeDiff,
  WORKTREE_REMOVE: RunnerRpcMethods.WorktreeRemove,
} as const;

export type RunnerMethod = (typeof RunnerMethod)[keyof typeof RunnerMethod];
